apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: pc-monitor
      defaultBucket: pc-metrics
    secureJsonData:
      token: pc-monitor-super-secret-token
    isDefault: true
